---
vpc_cidr: '10.46.0.0/16'
vpc_subnet_cidr: '10.46.10.0/24'
aws_region: 'us-west-2'
aws_az: 'us-west-2a'
bcit_subnet: '142.232.0.0/16'
vpc_prefix: 'ACIT4640'
ec2_ami_id: ami-01ed306a12b7d1c96
ec2_instance_name: ACIT4640_APP
ec2_instance_size: t2.micro
ec2_instance_storage_size: 8